import React, { useEffect, useState } from 'react';
import { Card, FormField, Loader } from '../components';
import { homepage } from '../assets';

const RenderCards = ({ data , title }) => {
    if(data?.length > 0) {
        return data.map((post) => <Card key={post._id} {...post} />)
    }

    return (
        <h2 className='mt-5 font-bold text-[#007c71] text-xl uppercase'>{title}</h2>
    )
}

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setSearchText] = useState('');
    const [searchTimeout, setSearchTimeout] = useState(null);
    const [searchedResults, setSearchedResults] = useState(null);

    const fetchPosts = async () => {
        setLoading(true);
    
        try {
          const response = await fetch('https://dalle-arbb.onrender.com/api/v1/post', {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json',
            },
          });
    
          if (response.ok) {
            // show new posts at the top
            const result = await response.json();
            setAllPosts(result.data.reverse());
          }
        } catch (err) {
          alert(err);
        } finally {
          setLoading(false);
        }
      };

    // User can type in matching name or prompt, wait 500miliseconds before display results
    const handleSearchChange = (e) => {
        // clear timeout everytime searching something new
        clearTimeout(searchTimeout);
        setSearchText(e.target.value);

        setSearchTimeout(setTimeout(() => {
                const searchedResult = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
                setSearchedResults(searchedResult);
            }, 500)
        );
    }
  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className="font-extrabold text-[#222328] text-[32px]">Start your AI art journey with Davolio today!</h1>
            <p className='mt-2 text-[#666e75] text-[16px] '>Browse through a collection of imaginative and visually stunning images generated by OpenAI's DALL-E AI</p>
        </div>

        <div className='flex flex-col mt-16 gap-8'>
            <FormField 
                labelName="Search posts"
                type="text"
                name="text"
                placeholder="Search for anything..."
                value={searchText}
                handleChange={handleSearchChange}
            />
            <img
                src={homepage}
                alt='homepage'
                className='w-full h-full sm:w-4/12 sm:h-4/12 object-contain'
            />
        </div>

        <div className='mt-4 sm:mt-10'>
            {loading ? (
            <div className="flex justify-center items-center">
                <Loader />
            </div>
            ) : (
                <>
                    {searchText && (
                        <h2 className="font-medium text-[#666e75] text-xl mb-3">
                            Showing Results for <span className='text-[#222328]'>{searchText}</span>
                        </h2>
                    )}
                    <div className="grid lg:grid-cols-4 sm:grid-cols3 xs:grid-cols-2 grid-cols-1 gap-3">
                        {searchText ? (
                            <RenderCards
                                data={searchedResults}
                                title="No Search Results Found"
                            />
                        ) : (
                            <RenderCards
                                data={allPosts}
                                title="No Posts Yet"
                            />
                        )}
                    </div>
                </>
            )}
        </div>
    </section>
  )
}

export default Home
